name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matrix:
    strategy:
      matrix:
        lib: [otelmiddleware, otelzerolog, otelslog, otellogrus]
    runs-on: ubuntu-latest
    name: "Build and test - ${{ matrix.lib }}"
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/setup-go@v3
        name: Set up Go
        with:
          go-version-file: "${{ matrix.lib }}/go.mod"
          # go-version: "1.20.6"

      - name: Build
        run: go build -v ./...
        working-directory: "${{ matrix.lib }}"

      - name: Test
        run: go test -v ./...
        working-directory: "${{ matrix.lib }}"
      
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-package: "./${{ matrix.lib }}/..."

#    - name: Install Dagger
#      uses: dagger/dagger-for-github@v3
#      with:
#        install-only: true
#
#    - name: Dagger project update
#      run: dagger project update
#
#    - name: Dagger do test
#      run: dagger do test --log-format plain


